image: debian

test:
  script:
    - apt-get update
    - apt-get -y install git build-essential pkg-config libsodium-dev clang
    - cd tests/native
    # The current Makefile setup fails to consider the vpaths intgroduced in
    # Makefile.libcose made available at lib build time; calling make in
    # different steps works around that.
    - make libs
    - make test-all-versions

pages:
  script:
    - apt-get update && apt-get -y install doxygen graphviz
    - cd doc && doxygen Doxyfile && cd ..
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

