image: debian

pages:
  script:
    - apt-get update && apt-get -y install doxygen
    - cd doc && doxygen Doxyfile && cd ..
    - mv doc/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master

